### ISSUE TITLE
Replace week_start integer with an enum

### ISSUE THREAD

**Issue by omid** [fmeringdal/nettu-scheduler#27]
It's unknown what the number is, for example, what is 0?
It's better to replace it with an enum, with weekdays.

For example:
```
WeekDay::Sat
...
```

**Comment by omid** [comment]
chrono package already has this, we need to use it and re-export the enum in the SDK:
https://docs.rs/chrono/0.4.19/chrono/enum.Weekday.html

**Comment by fmeringdal** [comment]
Same as the `rrule` crate: https://docs.rs/rrule/0.5.9/rrule/enum.Weekday.html
I dont remember the reason on top of my head why I chose to model the week start with a number, but I guess there is no good reason.

Another semi related thing is the `recurrence` attribute on `CalendarEvent` which should ideally be modelled as an rrule string which is well defined instead of a custom `Recurrence` struct. Google Calendar does this, but Outlook Calendar does not.
